"""alter_table_users_added_column_proxy_password_plain_and_proxy_password_hashed

Revision ID: 3c8a0268c835
Revises: e22f7b040ffa
Create Date: 2024-08-16 12:06:07.996950

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3c8a0268c835"
down_revision: Union[str, None] = "e22f7b040ffa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "proxy_password",
        new_column_name="proxy_password_plain",
        existing_type=sa.String(64),
        type_=sa.String(20),
    )
    op.add_column(
        "users",
        sa.Column("proxy_password_hashed", sa.String(length=64), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "proxy_password_plain",
        new_column_name="proxy_password",
        existing_type=sa.String(20),
        type_=sa.String(64),
    )
    op.drop_column("users", "proxy_password_hashed")
    # ### end Alembic commands ###
