"""alter_table_users_add_column_is_verified

Revision ID: 5610a5417898
Revises: 2b78b1247f2a
Create Date: 2024-08-31 18:48:55.304113

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql import expression

# revision identifiers, used by Alembic.
revision: str = "5610a5417898"
down_revision: Union[str, None] = "2b78b1247f2a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("otp_unique_id", "otp", ["id"])
    op.add_column("users", sa.Column("is_verified", sa.Boolean(), server_default=expression.true(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_verified")
    op.drop_constraint("otp_unique_id", "otp", type_="unique")
    # ### end Alembic commands ###
