"""add_column_hash_value_modems_table

Revision ID: 83f572529b3b
Revises: 456d541c9f25
Create Date: 2024-08-07 22:08:31.761544

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "83f572529b3b"
down_revision: Union[str, None] = "456d541c9f25"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("modems", sa.Column("hashed_value", sa.String(length=32), nullable=False, server_default=""))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("modems", "hashed_value")
    # ### end Alembic commands ###
