"""drop_table_admin_users

Revision ID: 8e6d563a93c9
Revises: f8fcd6a9fb7c
Create Date: 2024-08-12 21:30:43.471819

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8e6d563a93c9"
down_revision: Union[str, None] = "f8fcd6a9fb7c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("admins")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admins",
        sa.Column(
            "role",
            postgresql.ENUM("ADMIN", "REGULAR", name="userrole"),
            server_default=sa.text("'ADMIN'::userrole"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("email", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("hashed_password", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("created", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.Column("updated", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="admins_pkey"),
        sa.UniqueConstraint("email", name="admins_email_key"),
    )
    # ### end Alembic commands ###
