"""alter_table_users_alter_column_proxy_password_hash_type_remove_default_value

Revision ID: ba9a495aaf16
Revises: fecd7983d09f
Create Date: 2024-08-12 22:59:11.512349

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ba9a495aaf16"
down_revision: Union[str, None] = "fecd7983d09f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "proxy_password_hash_type",
        server_default=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "proxy_password_hash_type", server_default=sa.text("'MD5'::hashtype"))

    # ### end Alembic commands ###
