"""alter_table_users_alter_column_proxy_password

Revision ID: c55037af3f16
Revises: 11b1ad9f0880
Create Date: 2024-08-10 17:04:00.898662

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c55037af3f16"
down_revision: Union[str, None] = "11b1ad9f0880"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "proxy_password",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=64),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "proxy_password",
        existing_type=sa.String(length=64),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
