"""alter_table_modems_rename_column_public_server_ip_and_add_column_internal_server_ip

Revision ID: e22f7b040ffa
Revises: e6a1dba1f790
Create Date: 2024-08-16 11:03:59.573109

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e22f7b040ffa"
down_revision: Union[str, None] = "e6a1dba1f790"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("modems", "public_server_ip", new_column_name="external_server_ip")
    op.add_column("modems", sa.Column("internal_server_ip", postgresql.INET(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("modems", "external_server_ip", new_column_name="public_server_ip")
    op.drop_column("modems", "internal_server_ip")
    # ### end Alembic commands ###
