"""renamed_columns_ip_port_username_and_password

Revision ID: faf6fcb1e17f
Revises: 412117efac49
Create Date: 2024-08-07 11:43:47.385401

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "faf6fcb1e17f"
down_revision: Union[str, None] = "412117efac49"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("modems", "modem_ip", nullable=False, new_column_name="ip")
    op.alter_column("modems", "modem_port", nullable=False, new_column_name="port")
    op.alter_column("modems", "modem_password", nullable=True, new_column_name="password")
    op.alter_column("modems", "modem_username", nullable=True, new_column_name="username")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("modems", "ip", nullable=False, new_column_name="modem_ip")
    op.alter_column("modems", "port", nullable=False, new_column_name="modem_port")
    op.alter_column("modems", "password", nullable=True, new_column_name="modem_password")
    op.alter_column("modems", "username", nullable=True, new_column_name="modem_username")
    # ### end Alembic commands ###
