services:
  db:
    image: postgres:16.3-alpine
    ports:
      - 5432
    environment:
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_INITDB_ARGS="--data-checksums"
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$(cat /run/secrets/postgres_user) -d $$(cat /run/secrets/postgres_db)" ]
      interval: 10s
      timeout: 10s
      retries: 5  
    volumes:
      - pgdata:/var/lib/postgresql/data
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db
    networks:
      - backend

  backend:
    image: ghcr.io/sergey-vernyk/proxy_management:${IMAGE_BACKEND_TAG}
    command: >
      sh -c "cat /run/secrets/env_file > .env &&
      ./wait-for.sh db:5432 -- &&
      poetry run gunicorn main:app --bind=0.0.0.0:8000 --workers 2 --worker-class uvicorn.workers.UvicornWorker --forwarded-allow-ips='*' 
      "
    ports:
      - 8000
    volumes:
      - backend_media:/usr/src/app/backend/media
      - backend_static:/usr/src/app/backend/static
    secrets:
      - env_file
    deploy:
      update_config:
        order: start-first
    depends_on:
      - db
    networks:
      - backend

  nginx:
    image: ghcr.io/sergey-vernyk/reverse_proxy:${IMAGE_NGINX_TAG}
    volumes:
      - backend_media:/vol/web/media
      - backend_static:/vol/web/static
      - webroot:/var/www/certbot
      - certbot_data:/etc/letsencrypt
      - certbot_logs:/var/log/letsencrypt
      - proxy_dhparams:/vol/proxy
    environment:
      - DOMAIN=proxman.pp.ua
      - SERVER_PORT=443
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
    deploy:
      update_config:
        order: start-first
    secrets:
       - domain
    networks:
      - backend

volumes:
  pgdata:
    driver: local
  webroot:
    external: true
  certbot_data:
    external: true
  certbot_logs:
    driver: local
  backend_media:
    driver: local
  backend_static:
    driver: local
  proxy_dhparams:
    driver: local

networks:
  backend:
    driver: overlay
    attachable: true

# external=true for using docker secrets for services
secrets:
  postgres_db:
    external: true
  postgres_user:
    external: true
  postgres_password:
    external: true
  env_file:
    external: true
  domain:
    external: true
