[tool.poetry]
name = "asyncsocketexchange"
version = "0.1.0"
description = "Async interaction beetwen socket server and client"
authors = ["Sergey Vernigora <volt.awp@gmail.com>"]
readme = "README.md"
packages = [
    { include = "sockets" },
    { include = "users" },
    { include = "modems" },
    { include = "common" },
    { include = "logs" },
    { include = "auth" },
]

[tool.poetry.dependencies]
python = "^3.10"
python-dotenv = "^1.0.1"
click = "^8.1.7"
fastapi = "^0.112.0"
uvicorn = "^0.30.5"
sqlalchemy = "^2.0.31"
huawei-lte-api = "^1.9.3"
alembic = "^1.13.2"
email-validator = "^2.2.0"
pydantic-settings = "^2.4.0"
psycopg2-binary = "^2.9.9"
bcrypt = "^4.2.0"
python-jose = "^3.3.0"
python-multipart = "^0.0.9"
passlib = "^1.7.4"
websockets = "^12.0"
jinja2 = "^3.1.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
socket-server = "cli:cli_server"
