upstream socket_backend {
        server 127.0.0.1:8000;
}

server {
        if ($host = ${DOMAIN}) {
                return 301 https://$host$request_uri; 
        }

        server_name     ${DOMAIN} www.${DOMAIN};
        listen          80 default_server;

        location /.well-known/acme-challenge/ {
                allow all;
        }

        return 404;
}

server {
        server_name         ${DOMAIN} www.${DOMAIN};
        listen              ${PORT} ssl;
        ssl_certificate     /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem; 
        include             /etc/letsencrypt/options-ssl-nginx.conf;   
        ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;         
        server_tokens       off;
        proxy_set_header    Host                $host;
        proxy_set_header    X-Real-IP           $remote_addr;
        proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Proto   $scheme;

        map $server_port $forwarding_port {
                80              1;
                443             2;
                default         0;
        }

        if ($forwarding_port = 0) {
                proxy_set_header    X-Forwarded-Port $server_port;
        }


        # location for http        
        location / {
                proxy_pass      http://socket_backend;
        }

        # location for wesockets
        location /ws/ {
                proxy_pass http://socket_backend;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
        }
}