name: Setup Cloudflare Security Level
description: An action for Cloudflare security management.

on:
  workflow_call:
    inputs:
      security_level:
        type: choices
        description: "Security level to set (essentially_off, low, medium, hign, under_attack)"
        required: true
        options:
          - essentially_off
          - low
          - medium
          - hign
          - under_attack
        default: medium

runs:
  using: composite
  steps:
    - name: Configure Cloudflare Security Level
      shell: bash
      run: |
          curl -s --request PATCH \
            --url https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/settings/security_level \
            --header "Authorization: Bearer ${{ secrets.API_KEY_CLOUDFLARE }}" \
            --header "Content-Type: application/json" \
            --data '{"value": "'"${{ inputs.security_level }}"'"}' | jq
