"""create_tables_users_and_modems

Revision ID: 01d8a1275108
Revises: 
Create Date: 2024-08-04 19:55:31.404915

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy import func

# revision identifiers, used by Alembic.
revision: str = "01d8a1275108"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=50), nullable=False),
        sa.Column("login", sa.String(length=20), nullable=False),
        sa.Column("password", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "modems",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("modem_ip", sa.String(length=16), nullable=False),
        sa.Column("token", sa.String(length=32), nullable=False),
        sa.Column("bind_user_id", sa.Integer(), nullable=True),
        sa.Column("modem_username", sa.String(length=20), nullable=True),
        sa.Column("modem_password", sa.String(length=20), nullable=True),
        sa.Column("rebooted", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created", sa.DateTime(timezone=True), server_default=func.now(), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), onupdate=func.now(), nullable=True),
        sa.ForeignKeyConstraint(["bind_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("modems")
    op.drop_table("users")
    # ### end Alembic commands ###
