"""add_column_external_server_port_in_table_modems

Revision ID: 10e8b47cddc5
Revises: 5610a5417898
Create Date: 2024-10-09 15:53:27.454453

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "10e8b47cddc5"
down_revision: Union[str, None] = "5610a5417898"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "modems",
        sa.Column(
            "external_server_port",
            sa.Integer(),
            nullable=False,
            server_default="65000",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("modems", "external_server_port")
    # ### end Alembic commands ###
