"""moved_column_token_to_users_table

Revision ID: 112c36fc8e22
Revises: 01d8a1275108
Create Date: 2024-08-04 21:51:31.589140

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "112c36fc8e22"
down_revision: Union[str, None] = "01d8a1275108"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("token", sa.String(length=32), nullable=False))
    op.drop_column("modems", "token")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "token")
    op.add_column("modems", sa.Column("token", sa.String(32), nullable=False))
    # ### end Alembic commands ###
