"""alter_table_users_rename_columns

Revision ID: 11b1ad9f0880
Revises: 83f572529b3b
Create Date: 2024-08-10 14:53:02.633406

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "11b1ad9f0880"
down_revision: Union[str, None] = "83f572529b3b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "login", new_column_name="proxy_login")
    op.alter_column("users", "password", new_column_name="proxy_password")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "proxy_login", new_column_name="login")
    op.alter_column("users", "proxy_password", new_column_name="password")
    # ### end Alembic commands ###
