"""alter_table_users_alter_column_hashed_password_null

Revision ID: 1bd054f85c70
Revises: 10e8b47cddc5
Create Date: 2024-10-12 18:45:11.012033

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1bd054f85c70"
down_revision: Union[str, None] = "10e8b47cddc5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "hashed_password", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "hashed_password", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
