"""add_column_public_server_ip_to_modems_table

Revision ID: 20fabf318329
Revises: ba9a495aaf16
Create Date: 2024-08-13 19:37:54.316894

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "20fabf318329"
down_revision: Union[str, None] = "ba9a495aaf16"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("modems", sa.Column("public_server_ip", postgresql.INET(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("modems", "public_server_ip")
    # ### end Alembic commands ###
