"""add_column_modem_port_table_modems

Revision ID: 412117efac49
Revises: 112c36fc8e22
Create Date: 2024-08-06 10:44:22.209564

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "412117efac49"
down_revision: Union[str, None] = "112c36fc8e22"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("modems", sa.Column("modem_port", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("modems", "modem_port")
    # ### end Alembic commands ###
