"""alter_table_modems_alter_column_bind_user_id

Revision ID: 44093c65dd18
Revises: 722ceb970ea9
Create Date: 2024-08-11 12:16:20.072157

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "44093c65dd18"
down_revision: Union[str, None] = "722ceb970ea9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("modems_bind_user_id_fkey", "modems", "foreignkey")
    op.alter_column("modems", "bind_user_id", existing_type=sa.Integer(), type_=sa.Integer(), nullable=True)
    op.create_foreign_key("modems_bind_user_id_fkey", "modems", "users", ["bind_user_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("modems_bind_user_id_fkey", "modems", "foreignkey")
    op.alter_column("modems", "bind_user_id", existing_type=sa.Integer(), type_=sa.Integer(), nullable=False)
    op.create_foreign_key("modems_bind_user_id_fkey", "modems", "users", ["bind_user_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###
