"""alter_table_modems_add_column_external_server_host

Revision ID: 692e564f68da
Revises: 1bd054f85c70
Create Date: 2024-10-18 17:00:17.294966

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "692e564f68da"
down_revision: Union[str, None] = "1bd054f85c70"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "modems",
        sa.Column(
            "external_server_host",
            sa.String(length=253),
            nullable=False,
            server_default="http://example.com",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("modems", "external_server_host")
    # ### end Alembic commands ###
