"""alter_table_users_add_column_proxy_password_hash_type

Revision ID: 722ceb970ea9
Revises: d53f3d8366d4
Create Date: 2024-08-11 11:54:44.453011

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision: str = "722ceb970ea9"
down_revision: Union[str, None] = "d53f3d8366d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    hash_type_enum = ENUM("MD5", "SHA256", name="hashtype", create_type=False)

    # Create ENUM type if it does not exist
    op.execute("CREATE TYPE hashtype AS ENUM ('MD5', 'SHA256')")

    op.add_column("users", sa.Column("proxy_password_hash_type", hash_type_enum, nullable=False, server_default="MD5"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "proxy_password_hash_type")
    op.execute("DROP TYPE hashtype")
    # ### end Alembic commands ###
