"""alter_table_users_added_table_admins

Revision ID: 7326cf0e7161
Revises: 44093c65dd18
Create Date: 2024-08-11 13:18:58.631401

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy import func
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision: str = "7326cf0e7161"
down_revision: Union[str, None] = "44093c65dd18"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    user_role_enum = ENUM("ADMIN", "REGULAR", name="userrole", create_type=False)

    # Create ENUM type if it does not exist
    op.execute("CREATE TYPE userrole AS ENUM ('ADMIN', 'REGULAR')")
    op.create_table(
        "admins",
        sa.Column("role", user_role_enum, nullable=False, server_default="ADMIN"),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=50), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), server_default=func.now(), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), server_onupdate=func.now(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.drop_constraint("modems_bind_user_id_fkey", "modems", type_="foreignkey")
    op.create_foreign_key("modems_bind_user_id_fkey", "modems", "users", ["bind_user_id"], ["id"], ondelete="SET NULL")
    op.add_column("users", sa.Column("role", user_role_enum, nullable=False, server_default="REGULAR"))
    op.add_column("users", sa.Column("created", sa.DateTime(timezone=True), server_default=func.now(), nullable=False))
    op.add_column("users", sa.Column("updated", sa.DateTime(timezone=True), server_onupdate=func.now(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "updated")
    op.drop_column("users", "created")
    op.drop_column("users", "role")
    op.drop_constraint("modems_bind_user_id_fkey", "modems", type_="foreignkey")
    op.create_foreign_key("modems_bind_user_id_fkey", "modems", "users", ["bind_user_id"], ["id"], ondelete="SET NULL")
    op.drop_table("admins")
    # ### end Alembic commands ###
