"""alter_column_ip_modems_table

Revision ID: e6a1dba1f790
Revises: 20fabf318329
Create Date: 2024-08-13 21:28:12.498688

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e6a1dba1f790"
down_revision: Union[str, None] = "20fabf318329"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        ALTER TABLE modems
        ALTER COLUMN ip TYPE INET
        USING ip::inet
    """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        ALTER TABLE modems
        ALTER COLUMN ip TYPE VARCHAR(39)
        USING ip::text
    """
    )
    # ### end Alembic commands ###
