"""alter_table_modems_alter_column_hashed_value

Revision ID: f8fcd6a9fb7c
Revises: 7326cf0e7161
Create Date: 2024-08-11 15:26:33.863293

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f8fcd6a9fb7c"
down_revision: Union[str, None] = "7326cf0e7161"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "modems",
        "hashed_value",
        existing_type=sa.VARCHAR(length=32),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "modems",
        "hashed_value",
        existing_type=sa.VARCHAR(length=32),
        nullable=False,
        existing_server_default=sa.text("''::character varying"),
    )
    # ### end Alembic commands ###
