"""alter_table_users_alter_columns_token_proxy_login_proxy_password_proxy_password_hash_type_as_null

Revision ID: fecd7983d09f
Revises: 8e6d563a93c9
Create Date: 2024-08-12 22:30:12.782883

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fecd7983d09f"
down_revision: Union[str, None] = "8e6d563a93c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "token", existing_type=sa.VARCHAR(length=32), nullable=True)
    op.alter_column("users", "proxy_login", existing_type=sa.VARCHAR(length=20), nullable=True)
    op.alter_column("users", "proxy_password", existing_type=sa.VARCHAR(length=64), nullable=True)
    op.alter_column(
        "users",
        "proxy_password_hash_type",
        existing_type=postgresql.ENUM("MD5", "SHA256", name="hashtype"),
        nullable=True,
        existing_server_default=sa.text("'MD5'::hashtype"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "proxy_password_hash_type",
        existing_type=postgresql.ENUM("MD5", "SHA256", name="hashtype"),
        nullable=False,
        existing_server_default=sa.text("'MD5'::hashtype"),
    )
    op.alter_column("users", "proxy_password", existing_type=sa.VARCHAR(length=64), nullable=False)
    op.alter_column("users", "proxy_login", existing_type=sa.VARCHAR(length=20), nullable=False)
    op.alter_column("users", "token", existing_type=sa.VARCHAR(length=32), nullable=False)
    # ### end Alembic commands ###
