name: Deploy Project To Own Server

on:
  workflow_run:
    workflows: 
      - Qodana
      - Run Tests
    types: ["completed"]
    branches:
      - main

  workflow_dispatch:

env:
  SUPERVISOR_PROGRAM_NAME: ${{ vars.SUPERVISOR_PROGRAM_NAME }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: production
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up SSH keys
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
      
        # add the host to known_hosts
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        
        # add the key to the agent
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa
    
    - name: Connect to server and pull last changes from git
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
          cd '${{ secrets.WORK_DIR }}' || exit 1 &&
          git remote set-url origin git@github.com:${{ github.repository }}.git &&
          git checkout '${{ secrets.MAIN_BRANCH }}' &&
          git pull origin '${{ secrets.MAIN_BRANCH }}' &&
          exit
        "

    - name: Restart Gunicorn
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
          cd '${{ secrets.WORK_DIR }}/backend' &&
          /home/${{ secrets.SSH_USER }}/.local/bin/poetry install --no-interaction || exit 1 &&
          cd ./deploy_config || exit 1 &&
          chmod 755 gunicorn_actions_after_deploy.sh && 
          ./gunicorn_actions_after_deploy.sh '${{ env.SUPERVISOR_PROGRAM_NAME }}' || exit 1
        "

    - name: Cleanup
      run: rm -rf ~/.ssh
