name: Deploy Project To Own Server

on:
  workflow_run:
    workflows: 
      - Qodana
      - Run Tests
    types: ["completed"]
    branches:
      - main

  workflow_dispatch:

env:
  SUPERVISOR_PROGRAM_NAME: ${{ vars.SUPERVISOR_PROGRAM_NAME }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: production
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up SSH keys
      uses: ./.github/workflows/setup_ssh.yml
      with:
        branch: "pre-deploy"
        ssh_user: ${{ secrets.SSH_USER }}
        ssh_host: ${{ secrets.SSH_HOST }}
        work_dir: ${{ secrets.WORK_DIR }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: Connect to server and pull last changes from git
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
          cd '${{ secrets.WORK_DIR }}' || exit 1 &&
          git remote set-url origin git@github.com:${{ github.repository }}.git &&
          git checkout '${{ secrets.MAIN_BRANCH }}' &&
          git pull origin '${{ secrets.MAIN_BRANCH }}' &&
          exit
        "

    - name: Restart Gunicorn
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
          cd '${{ secrets.WORK_DIR }}/backend' &&
          /home/${{ secrets.SSH_USER }}/.local/bin/poetry install --no-interaction || exit 1 &&
          cd ./deploy_config || exit 1 &&
          chmod 755 gunicorn_actions_after_deploy.sh && 
          ./gunicorn_actions_after_deploy.sh '${{ env.SUPERVISOR_PROGRAM_NAME }}' || exit 1
        "

    - name: Cleanup
      run: rm -rf ~/.ssh
