name: Pre-Deploy to Staging

on:
    push:
        branches:
        - pre-deploy
    pull_request:
        branches:
        - pre-deploy
  
jobs:
  pre-deploy:
    name: Pre-Deploy to Staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up SSH keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      - name: Pull Changes and Start Staging Server
        env:
            SSH_USER: ${{ secrets.SSH_USER }}
            SSH_HOST: ${{ secrets.SSH_HOST }}
            WORK_DIR: ${{ secrets.WORK_DIR }}
            REPO_NAME: ${{ github.repository }}
        run: |
          cd "${{ secrets.WORK_DIR }}/backend/deploy_config"
          chmod +x start_staging_server.sh          
          ./start_staging_server.sh ${{ env.SSH_USER }} ${{ env.SSH_HOST }} ${{ env.WORK_DIR }} ${{ env.REPO_NAME }}
        
      - name: Wait for Server Startup
        run: |
              for i in {1..5}; do
                response_code=$(curl -s -o /dev/null -w "%{http_code}" ${{ secrets.STAGE_BASE_URL }}/health_check)
                if [ "$response_code" -eq 200 ]; then
                  echo "Server is up!"
                  break
                fi
                echo "Waiting for server..."
                sleep 5
              done
              if [ "$response_code" -ne 200 ]; then
                echo "Server did not start in time."
                exit 1
              fi
        
      - name: Health Check
        run: |
              response_code=$(curl -s -w "%{http_code}" -o /tmp/health_response.json ${{ secrets.STAGE_BASE_URL }}/health_check)
              if [ "$response_code" -ne 200 ]; then
                  echo "Health check failed with status $response_code"
                  exit 1
              else
                  echo "Health check passed!"
                  echo "Server Health Status:"
                  cat /tmp/health_response.json | jq .
              fi
        
      - name: Cleanup
        run: rm -rf ~/.ssh
        