name: Pre-Deploy to Staging

on:
    push:
        branches:
        - pre-deploy
    pull_request:
        branches:
        - pre-deploy
  
jobs:
  setup-ssh:
    uses: ./.github/workflows/setup_ssh.yml
    name: Pre-Deploy
    secrets:
      ssh_user: ${{ secrets.SSH_USER }}
      ssh_host: ${{ secrets.SSH_HOST }}
      work_dir: ${{ secrets.WORK_DIR }}
      ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
      gh_artifacts_ghg_private: ${{ secrets.GH_ARTIFACTS_GHG_PRIVATE }}
      gh_artifacts_ghg_pub: ${{ secrets.GH_ARTIFACTS_GHG_PUB }}
      gpg_id: ${{ secrets.GPG_ID }}

  pre-deploy:
    needs: setup-ssh
    name: Pre-Deploy to Staging
    runs-on: ubuntu-latest

    steps:
      - name: Download SSH Config Artifact
        uses: actions/download-artifact@v4
        with:
            name: ssh-config
            
      - name: Restore SSH Config
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GH_ARTIFACTS_GHG_PRIVATE }}" | gpg --import
          echo "${{ secrets.GH_ARTIFACTS_GHG_PUB }}" | gpg --import

          echo "$(gpg --list-keys --fingerprint \
            | grep -B 1 '${{ secrets.GPG_ID }}' \
            | head -1 \
            | tr -d '[:space:]' \
            | cut -d '=' -f 2):6" \
            | gpg --import-ownertrust

          tar -xzf ssh_config.tar.gz.asc -C ~/.ssh
          gpg --decrypt ssh_config.tar.gz.asc > ssh_config.tar.gz

          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Pull Changes and Start Staging Server
        run: |
          cd ./backend/deploy_config
          chmod +x start_staging_server.sh
          ./start_staging_server.sh ${{ secrets.SSH_USER }} ${{ secrets.SSH_HOST }} ${{ secrets.WORK_DIR }} ${{ github.repository }}

      - name: Disable Cloudflare Under Attack Mode
        if: ${{ vars.ENABLED_UNDER_ATTACK == 'true' }}
        uses: ./.github/actions/setup_cloudflare_security
        with:
          security_level: medium
          cloudflare_zone_id: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          api_key_cloudflare: ${{ secrets.API_KEY_CLOUDFLARE }}

      - name: Wait for Server Startup
        run: |
          for i in {1..5}; do
            response_code=$(curl -s -o /dev/null -w "%{http_code}" ${{ secrets.STAGE_BASE_URL }}/health_check)
            if [ "$response_code" -eq 200 ]; then
              echo "Server is up!"
              break
            fi
            echo "Waiting for server..."
            sleep 5
          done
          if [ "$response_code" -ne 200 ]; then
            echo "Server did not start in time."
            exit 1
          fi

      - name: Delay for Security Mode Change
        if: ${{ vars.ENABLED_UNDER_ATTACK == 'true' }}
        run: sleep 10 
          
      - name: Health Check
        run: |
          response_code=$(curl -s -w "%{http_code}" -o /tmp/stage_health_response.json ${{ secrets.STAGE_BASE_URL }}/health_check)
          if [ "$response_code" -ne 200 ]; then
              echo "Health check failed with status $response_code"
              exit 1
          else
              echo "Health check passed!"
              echo "Server Health Status:"
              cat /tmp/stage_health_response.json | jq
          fi

      - name: Enable Cloudflare Under Attack Mode
        if: ${{ vars.ENABLED_UNDER_ATTACK == 'true' }}
        uses: ./.github/actions/setup_cloudflare_security
        with:
            security_level: under_attack
            cloudflare_zone_id: ${{ secrets.CLOUDFLARE_ZONE_ID }}
            api_key_cloudflare: ${{ secrets.API_KEY_CLOUDFLARE }}
        
      - name: Cleanup
        run: rm -rf ~/.ssh
        