name: Pre-Deploy to Staging

on:
  # workflow_run:
  #   workflows: 
  #     - Run Tests
  #   types: ["completed"]
  #   branches:
  #     - pre-deploy
  push:
    branches:
      - main

env:
  BACKEND_IMAGE_NAME: proxy_management
  NGINX_IMAGE_NAME: reverse_proxy
  REGISTRY: ghcr.io
  BRANCH: main
  
jobs:
  setup-ssh:
    uses: ./.github/workflows/setup_ssh.yml
    name: Pre-Deploy
    secrets:
      ssh_user: ${{ secrets.SSH_USER }}
      ssh_host: ${{ secrets.SSH_HOST }}
      work_dir: ${{ secrets.WORK_DIR }}
      ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
      gh_artifacts_gpg_private: ${{ secrets.GH_ARTIFACTS_GPG_PRIVATE }}
      gh_artifacts_gpg_public: ${{ secrets.GH_ARTIFACTS_GPG_PUBLIC }}
      gpg_id: ${{ secrets.GPG_ID }}

  build-push-image:
    runs-on:
      ubuntu-latest

    outputs:
      backend_image_tag: ${{ steps.meta-backend-image.outputs.tags }}
      nginx_image_tag: ${{ steps.meta-nginx-image.outputs.tags }}

    defaults:
      run:
        shell: sh
        working-directory: ./backend

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Metadata for Docker Backend image
        id: meta-backend-image
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.BACKEND_IMAGE_NAME }}
          labels: 
            org.opencontainers.image.licenses=MIT
            org.opencontainers.image.description=Image with backend and frontend implementation for proxy management
          tags: |
            type=sha

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Backend image
        uses: docker/build-push-action@v6
        with:
          context: backend
          file: backend/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-backend-image.outputs.tags }}
          labels: ${{ steps.meta-backend-image.outputs.labels }}

      - name: Extract Metadata for Docker Backend image
        id: meta-nginx-image
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.NGINX_IMAGE_NAME }}
          labels: 
            org.opencontainers.image.licenses=MIT
            org.opencontainers.image.description=Image with custom Nginx configuration
          tags: |
            type=sha

      - name: Build and push Nginx image
        uses: docker/build-push-action@v6
        with:
          context: backend/deploy_config/nginx
          file: backend/deploy_config/nginx/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-nginx-image.outputs.tags }}
          labels: ${{ steps.meta-nginx-image.outputs.labels }}

  pre-deploy:
    needs:
      - setup-ssh
      - build-push-image

    name: Pre-Deploy to Staging
    runs-on: ubuntu-latest

    # defaults:
    #   run:
    #     shell: sh
    #     working-directory: ./backend

    steps:
      - name: Download SSH Config Artifact
        uses: actions/download-artifact@v4
        with:
            name: ssh-config
            
      - name: Setup GPG
        run: |
          echo "${{ secrets.GH_ARTIFACTS_GPG_PRIVATE }}" | gpg --import
          echo "${{ secrets.GH_ARTIFACTS_GPG_PUBLIC }}" | gpg --import

          echo "$(gpg --list-keys --fingerprint \
            | grep -B 1 '${{ secrets.GPG_ID }}' \
            | head -1 \
            | tr -d '[:space:]' \
            | cut -d '=' -f 2):6" | gpg --import-ownertrust
            
      - name: Restore SSH Config
        run: |
          mkdir -p ~/.ssh
          gpg --decrypt ssh_config.tar.gz.asc > ssh_config.tar.gz
          tar -xzf ssh_config.tar.gz -C ~/.ssh
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Pull Changes and Start Staging Server
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
          cd ./backend &&
          sed -i 's/^IMAGE_BACKEND_TAG=.*/IMAGE_BACKEND_TAG=${{ needs.build-push-image.outputs.backend_image_tag }}/' .env &&
          sed -i 's/^IMAGE_NGINX_TAG=.*/IMAGE_NGINX_TAG=${{ needs.build-push-image.outputs.nginx_image_tag }}/' .env &&
          source .env &&
          if docker secret ls --format '{{.Name}}' | grep -q "env_file"; then docker secret rm env_file; fi &&
          docker secret create env_file .env &&
          git checkout ${{ env.BRANCH }} &&
          git pull origin ${{ env.BRANCH }} &&
          docker stack deploy --compose-file docker-compose.yml fastapi --with-registry-auth
          "

          # cd ./backend/deploy_config
          # chmod +x start_staging_server.sh
          # ./start_staging_server.sh ${{ secrets.SSH_USER }} ${{ secrets.SSH_HOST }} ${{ secrets.WORK_DIR }} ${{ github.repository }}

      - name: Disable Cloudflare Under Attack Mode
        if: ${{ vars.ENABLED_UNDER_ATTACK == 'true' }}
        uses: ./.github/actions/setup_cloudflare_security
        with:
          security_level: medium
          cloudflare_zone_id: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          api_key_cloudflare: ${{ secrets.API_KEY_CLOUDFLARE }}

      # - name: Wait for Server Startup
      #   run: |
      #     for i in {1..5}; do
      #       response_code=$(curl -s -o /dev/null -w "%{http_code}" ${{ secrets.STAGE_BASE_URL }}/health_check)
      #       if [ "$response_code" -eq 200 ]; then
      #         echo "Server is up!"
      #         break
      #       fi
      #       echo "Waiting for server..."
      #       sleep 5
      #     done
      #     if [ "$response_code" -ne 200 ]; then
      #       echo "Server did not start in time."
      #       exit 1
      #     fi

      # - name: Delay for Security Mode Change
      #   if: ${{ vars.ENABLED_UNDER_ATTACK == 'true' }}
      #   run: sleep 10 
          
      # - name: Health Check
      #   run: |
      #     response_code=$(curl -s -w "%{http_code}" -o /tmp/stage_health_response.json ${{ secrets.STAGE_BASE_URL }}/health_check)
      #     if [ "$response_code" -ne 200 ]; then
      #         echo "Health check failed with status $response_code"
      #         exit 1
      #     else
      #         echo "Health check passed!"
      #         echo "Server Health Status:"
      #         cat /tmp/stage_health_response.json | jq
      #     fi

      - name: Enable Cloudflare Under Attack Mode
        if: ${{ vars.ENABLED_UNDER_ATTACK == 'true' }}
        uses: ./.github/actions/setup_cloudflare_security
        with:
            security_level: under_attack
            cloudflare_zone_id: ${{ secrets.CLOUDFLARE_ZONE_ID }}
            api_key_cloudflare: ${{ secrets.API_KEY_CLOUDFLARE }}
        
      - name: Cleanup
        run: rm -rf ~/.ssh
        
