name: Pre-Deploy to Staging

on:
  # workflow_run:
  #   workflows: 
  #     - Run Tests
  #   types: ["completed"]
  #   branches:
  #     - pre-deploy
  push:
    branches:
      - main

env:
  BACKEND_IMAGE_NAME: proxy_management
  NGINX_IMAGE_NAME: reverse_proxy
  REGISTRY: ghcr.io
  
jobs:
  setup-ssh:
    uses: ./.github/workflows/setup_ssh.yml
    name: Pre-Deploy
    secrets:
      ssh_user: ${{ secrets.SSH_USER }}
      ssh_host: ${{ secrets.SSH_HOST }}
      work_dir: ${{ secrets.WORK_DIR }}
      ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
      gh_artifacts_gpg_private: ${{ secrets.GH_ARTIFACTS_GPG_PRIVATE }}
      gh_artifacts_gpg_public: ${{ secrets.GH_ARTIFACTS_GPG_PUBLIC }}
      gpg_id: ${{ secrets.GPG_ID }}

  build-push-image:
    runs-on:
      ubuntu-latest

    defaults:
      run:
        shell: sh
        working-directory: ./backend

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Extract Metadata for Docker Backend image
        id: meta-backend-image
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.BACKEND_IMAGE_NAME }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: backend/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-backend-image.outputs.tags }}
          labels: ${{ steps.meta-backend-image.outputs.labels }}

      - name: Extract Metadata for Docker Backend image
        id: meta-nginx-image
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.NGINX_IMAGE_NAME }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Build and push nginx image
        uses: docker/build-push-action@v6
        with:
          file: ./deploy_config/nginx/Dockerfile
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-nginx-image.outputs.tags }}
          labels: ${{ steps.meta-nginx-image.outputs.labels }}

      # - name: Build the Docker image for backend
      #   run: docker build . --file Dockerfile --tag ghcr.io/${{ github.actor }}/${{ env.BACKEND_IMAGE_NAME }}:latest
      # - name: Build the Docker image for Nginx
      #   run: |
      #     cd ./deploy_config/nginx
      #     docker build . --file Dockerfile --no-cache --tag ghcr.io/${{ github.actor }}/${{ env.NGINX_IMAGE_NAME }}:latest
      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      # - name: Push the Docker images to the GitHub registry
      #   run: | 
      #     docker push ghcr.io/${{ github.actor }}/${{ env.BACKEND_IMAGE_NAME }}:latest
      #     docker push ghcr.io/${{ github.actor }}/${{ env.NGINX_IMAGE_NAME }}:latest

  pre-deploy:
    needs:
      - setup-ssh
      - build-push-image

    name: Pre-Deploy to Staging
    runs-on: ubuntu-latest

    steps:
      - name: Download SSH Config Artifact
        uses: actions/download-artifact@v4
        with:
            name: ssh-config
            
      - name: Setup GPG
        run: |
          echo "${{ secrets.GH_ARTIFACTS_GPG_PRIVATE }}" | gpg --import
          echo "${{ secrets.GH_ARTIFACTS_GPG_PUBLIC }}" | gpg --import

          echo "$(gpg --list-keys --fingerprint \
            | grep -B 1 '${{ secrets.GPG_ID }}' \
            | head -1 \
            | tr -d '[:space:]' \
            | cut -d '=' -f 2):6" | gpg --import-ownertrust
            
      - name: Restore SSH Config
        run: |
          mkdir -p ~/.ssh
          gpg --decrypt ssh_config.tar.gz.asc > ssh_config.tar.gz
          tar -xzf ssh_config.tar.gz -C ~/.ssh
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Pull Changes and Start Staging Server
        run: |
          cd ./backend/deploy_config
          chmod +x start_staging_server.sh
          ./start_staging_server.sh ${{ secrets.SSH_USER }} ${{ secrets.SSH_HOST }} ${{ secrets.WORK_DIR }} ${{ github.repository }}

      - name: Disable Cloudflare Under Attack Mode
        if: ${{ vars.ENABLED_UNDER_ATTACK == 'true' }}
        uses: ./.github/actions/setup_cloudflare_security
        with:
          security_level: medium
          cloudflare_zone_id: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          api_key_cloudflare: ${{ secrets.API_KEY_CLOUDFLARE }}

      - name: Wait for Server Startup
        run: |
          for i in {1..5}; do
            response_code=$(curl -s -o /dev/null -w "%{http_code}" ${{ secrets.STAGE_BASE_URL }}/health_check)
            if [ "$response_code" -eq 200 ]; then
              echo "Server is up!"
              break
            fi
            echo "Waiting for server..."
            sleep 5
          done
          if [ "$response_code" -ne 200 ]; then
            echo "Server did not start in time."
            exit 1
          fi

      - name: Delay for Security Mode Change
        if: ${{ vars.ENABLED_UNDER_ATTACK == 'true' }}
        run: sleep 10 
          
      - name: Health Check
        run: |
          response_code=$(curl -s -w "%{http_code}" -o /tmp/stage_health_response.json ${{ secrets.STAGE_BASE_URL }}/health_check)
          if [ "$response_code" -ne 200 ]; then
              echo "Health check failed with status $response_code"
              exit 1
          else
              echo "Health check passed!"
              echo "Server Health Status:"
              cat /tmp/stage_health_response.json | jq
          fi

      - name: Enable Cloudflare Under Attack Mode
        if: ${{ vars.ENABLED_UNDER_ATTACK == 'true' }}
        uses: ./.github/actions/setup_cloudflare_security
        with:
            security_level: under_attack
            cloudflare_zone_id: ${{ secrets.CLOUDFLARE_ZONE_ID }}
            api_key_cloudflare: ${{ secrets.API_KEY_CLOUDFLARE }}
        
      - name: Cleanup
        run: rm -rf ~/.ssh
        
