name: SSH Setup 

on:
  workflow_call:
    secrets:
      ssh_user:
        description: "SSH username for the server"
        required: true
      ssh_host:
        description: "Server hostname or IP"
        required: true
      work_dir:
        description: "Directory on the server where the code should be pulled"
        required: true
      ssh_private_key:
        description: "Private SSH key for authentication"
        required: true
      gh_artifacts_gpg_private:
        description: Private key for GPG encryption/decryption.
        required: true
      gh_artifacts_gpg_public:
        description: Public key fo GPG encryption/decryption.
        required: true
      gpg_id:
        description: GPG identifier for the key (email or ID).
        required: true
      
jobs:
  ssh-setup:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ssh_private_key }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.ssh_host }} >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
      
      - name: Setup GPG
        run: |
          echo "${{ secrets.gh_artifacts_gpg_private }}" | gpg --import
          echo "${{ secrets.gh_artifacts_gpg_public }}" | gpg --import

          echo "$(gpg --list-keys --fingerprint \
            | grep -B 1 '${{ secrets.gpg_id }}' \
            | head -1 \
            | tr -d '[:space:]' \
            | cut -d '=' -f 2):6" | gpg --import-ownertrust
 
      - name: Save SSH Configuration as Artifacts
        run: |
          tar -czf ssh_config.tar.gz -C ~/.ssh .          
          gpg --encrypt -r ${{ secrets.gpg_id }} -a ssh_config.tar.gz

      - name: Upload SSH Config Artifact
        uses: actions/upload-artifact@v4
        with:
            name: ssh-config
            path: ssh_config.tar.gz.asc
            if-no-files-found: error