name: SSH Setup

on:
  workflow_call:
    secrets:
      ssh_user:
        description: SSH username for the server.
        required: true
      ssh_host:
        description: Server hostname or IP.
        required: true
      ssh_private_key:
        description: Private SSH key for authentication.
        required: true
      gh_artifacts_gpg_private:
        description: Private key for GPG encryption/decryption for ssh config.
        required: true
      gh_artifacts_gpg_public:
        description: Public key fo GPG encryption/decryption for ssh config.
        required: true
      gpg_id:
        description: GPG identifier for the key (email or ID).
        required: true
      
jobs:
  ssh-setup:
    runs-on: ubuntu-latest

    steps:
      - name: Set Up SSH Keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ssh_private_key }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.ssh_host }} >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
      
      - name: Setup GPG
        run: |
          echo "${{ secrets.gh_artifacts_gpg_private }}" | gpg --import
          echo "${{ secrets.gh_artifacts_gpg_public }}" | gpg --import

          FPR=$(gpg --with-colons --list-keys "${{ secrets.gpg_id }}" | awk -F: '/^fpr:/ {print $10; exit}')
          echo "${FPR}:6:" | gpg --import-ownertrust
          
      - name: Encrypt And Save SSH Configuration As Artifacts
        run: |
          tar -czf ssh_config.tar.gz -C ~/.ssh .          
          gpg --encrypt -r ${{ secrets.gpg_id }} -a ssh_config.tar.gz

      - name: Upload SSH Config Artifact
        uses: actions/upload-artifact@v4
        with:
            name: ssh-config
            path: ssh_config.tar.gz.asc
            if-no-files-found: error