name: Run Tests

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        poetry-version: ["1.8.3"]
        python-version: ["3.12"]

    services:
      postgres:
        image: postgres:16.3-alpine
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    defaults:
      run:
        shell: bash
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create postgres user with 'CREATEDB' privilege
        run: |
          sudo docker exec ${{ job.services.postgres.id }} sh -c "psql -U postgres -p 5432 -c 'CREATE USER ${{ secrets.DATABASE_USER }} WITH PASSWORD '\''${{ secrets.DATABASE_PASSWORD }}'\'' CREATEDB;'"
          sudo docker exec ${{ job.services.postgres.id }} sh -c "psql -U postgres -p 5432 -c 'CREATE DATABASE ${{ secrets.DATABASE_NAME }} OWNER ${{ secrets.DATABASE_USER }};'"
          sudo docker exec ${{ job.services.postgres.id }} sh -c "psql -U postgres -p 5432 -c 'CREATE USER ${{ secrets.DATABASE_USER_TEST }} WITH PASSWORD '\''${{ secrets.DATABASE_PASSWORD_TEST}}'\'' CREATEDB;'"
          sudo docker exec ${{ job.services.postgres.id }} sh -c "psql -U postgres -p 5432 -c 'CREATE DATABASE ${{ secrets.DATABASE_NAME_TEST }} OWNER ${{ secrets.DATABASE_USER_TEST }};'"

      - name: Cache poetry installation
        id: cache-poetry
        uses: actions/cache@v4
        with:
          path: ~/.local
          key: python-${{ matrix.python-version }}-poetry-v${{ matrix.poetry-version }}

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: python-${{ matrix.python-version }}-pydeps-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: poetry install --no-root --no-interaction

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd):$PYTHONPATH" >> $GITHUB_ENV

      - name: Create env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Test with pytest and coverage
        run: poetry run pytest --cov
