name: Test FastAPI Application

on:
  push:
    branches:
      - development
      - main
    paths:
      - src/**
      - tests/**
  pull_request:
    branches:
      - development
      - main

  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        poetry-version: ["2.1.4"]
        python-version: ["3.12"]

    services:
      postgres:
        image: postgres:16.3-alpine
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - uses: actions/checkout@v4
      - name: Set Up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create Postgres User With 'CREATEDB' Privilege
        run: |
          sudo docker exec ${{ job.services.postgres.id }} sh -c "psql -U postgres -p 5432 -c 'CREATE USER ${{ secrets.DATABASE_USER }} WITH PASSWORD '\''${{ secrets.DATABASE_PASSWORD }}'\'' CREATEDB;'"
          sudo docker exec ${{ job.services.postgres.id }} sh -c "psql -U postgres -p 5432 -c 'CREATE DATABASE ${{ secrets.DATABASE_NAME }} OWNER ${{ secrets.DATABASE_USER }};'"
          sudo docker exec ${{ job.services.postgres.id }} sh -c "psql -U postgres -p 5432 -c 'CREATE USER ${{ secrets.DATABASE_USER_TEST }} WITH PASSWORD '\''${{ secrets.DATABASE_PASSWORD_TEST}}'\'' CREATEDB;'"
          sudo docker exec ${{ job.services.postgres.id }} sh -c "psql -U postgres -p 5432 -c 'CREATE DATABASE ${{ secrets.DATABASE_NAME_TEST }} OWNER ${{ secrets.DATABASE_USER_TEST }};'"

      - name: Cache Poetry Installation
        id: cache-poetry
        uses: actions/cache@v4
        with:
          path: ~/.local
          key: python-${{ matrix.python-version }}-poetry-v${{ matrix.poetry-version }}

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry

      - name: Cache Dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: python-${{ matrix.python-version }}-pydeps-${{ hashFiles('**/poetry.lock') }}

      - name: Install Dependencies
        run: poetry install --no-root --no-interaction

      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=$(pwd)/src:$PYTHONPATH" >> $GITHUB_ENV

      - name: Create Env File
        working-directory: src/proxy_management
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Pytest And Coverage
        run: poetry run pytest --cov
